#+author: Indigo Paige
#+title:  nixie

* Synopsis
Nixie is a small functional programming language made to be as close to lambda calculus as possible, whilst also being a powerful and pragmatic high level programming language that can get real world work done.

* Structure
Nixie is structured in a few main parts that are called source components.
Below show these source components and how they work together to build the language.

** Expression
Nixie has many different kinds of expressions

*** Application
#+begin_src
  f x
  f x y
  f x y ... z
#+end_src
*** Lambda
#+begin_src
  x.+ x 1
  x.y.+ x y
#+end_src
*** Let
#+begin_src
  let x = y in z x
#+end_src
*** If
#+begin_src
  if true then x else y
#+end_src
** Pattern
Patterns in nixie are used to bind values to variables and destructure native structures.

*** Record Type
#+begin_src
 (A { x, y, z }) 
#+end_src
*** Unit Type
#+begin_src
  (A x)
#+end_src
*** Variable
#+begin_src
  x
#+end_src
*** Tuple
#+begin_src
  (x, y)
#+end_src
*** List
#+begin_src
  [a, b]
#+end_src
*** Name
#+begin_src
  both@(x, y)
#+end_src
** Type
Nixie types are simply records or unit types that have
at least one field.

*** Record
#+begin_src
  type point
    = Point { x : int, y : int }
#+end_src

*** Unit
#+begin_src
  type point
  
#+end_src
