spec-version: 0.36.0

default-extensions:
        - GeneralizedNewtypeDeriving
        - MultiParamTypeClasses
        - ImportQualifiedPost
        - OverloadedStrings
        - FlexibleContexts
        - TypeApplications
        - PatternSynonyms
        - ConstraintKinds
        - TemplateHaskell
        - NamedFieldPuns
        - TypeOperators
        - DeriveGeneric
        - LambdaCase
        - RankNTypes
        - DataKinds
        - Arrows
        - GADTs

dependencies:
        - megaparsec
        - containers
        - scientific
        - effectful
        - llvm-tf
        - some
        - base
        - lens
        - mtl

library:
        source-dirs: src